### PR TITLE
Rebase dekn#8065

### PR DESCRIPTION
**Pull request by agateaux**
To address CVEs https://github.com/plotly/dekn/issues/8065

### CODE REVIEW

**Comment by agateaux** [comment]
No more high or critical CVE:

```
cnb/buildpacks/paketo-buildpacks_pip-install/5.4.0/bin/run (gobinary)
=====================================================================
Total: 5 (UNKNOWN: 0, LOW: 0, MEDIUM: 5, HIGH: 0, CRITICAL: 0)

```

**Review by BRONSOLO — APPROVED** [review]
🚀

**Review by BRONSOLO — COMMENTED** [review]
I created a new `main` from the latest 5.3-sp-release branch and so now there are conflicts that must be addressed. I approved to soon.

**Comment by agateaux** [comment]
> I created a new `main` from the latest 5.3-sp-release branch and so now there are conflicts that must be addressed. I approved to soon.

Ok, I rebased from main. Could be ready to merge

**Pull request merged**
